using UnityEngine;

public class MapManager : MonoBehaviour
{
    private static MapManager _instance;

    public static MapManager Instance
    {
        get
        {
            if (_instance == null)
            {
                _instance = FindFirstObjectByType<MapManager>();
                if (_instance == null)
                {
                    GameObject go = new GameObject("MapManager_AutoGenerated");
                    _instance = go.AddComponent<MapManager>();
                }
            }
            return _instance;
        }
    }

    [Header("Stage Clear Flags")]
    public bool stage1Clear = false;
    public bool stage2Clear = false;
    public bool stage3Clear = false;

    [Header("Current Active Stage")]
    // 현재 도전 중인 스테이지 번호 (1, 2, 3)
    public int currentStage = 1;

    private void Awake()
    {
        if (_instance != null && _instance != this)
        {
            Destroy(gameObject);
            return;
        }
        _instance = this;
        DontDestroyOnLoad(gameObject);
    }

    // MapController에서 버튼을 누를 때 호출하여 현재 스테이지 값을 확정지음
    public void StartBattle(int stageNum)
    {
        currentStage = stageNum;
        Debug.Log($"[MapManager] 전투 시작 - 스테이지 {currentStage} 설정 완료");
    }

    // 전투 승리 시 호출되어 플래그를 세우고 자동 저장 진행
    public void OnBattleVictory()
    {
        if (currentStage == 1) stage1Clear = true;
        else if (currentStage == 2) stage2Clear = true;
        else if (currentStage == 3) stage3Clear = true;

        Debug.Log($"[MapManager] 스테이지 {currentStage} 클리어 성공!");

        if (SaveManager.Instance != null)
        {
            SaveManager.Instance.SaveGame();
        }
    }
}